version: '3'

services:
  keycloak-demo:
    image: quay.io/keycloak/keycloak:25.0
    ports:
      - 8080:8080
    command: start-dev
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_DB=postgres
      - KC_DB_URL=jdbc:postgresql://postgres:5432/keycloak
      - KC_DB_USERNAME=keycloak
      - KC_DB_PASSWORD=admin    
    depends_on:
      postgres:
        condition: service_healthy        
        

  postgres:
    image: postgres:16  
    ports:
      - "5432:5432"  
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: admin
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "db_prod"]
      interval: 10s
      timeout: 10s
      retries: 3      
  
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "9000:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: thiago@portaldoseller.com.br
      PGADMIN_DEFAULT_PASSWORD: 631fF3005*